Adding Custom S2I Image to the Project Catalog
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In the last lab to
link:https://openshift-tab.ocp.hcs-company.com/workshop/ocptab/lab/14-Using-a-Custom-S2I-Image[Using Custom S2I Image], we used
the S2I image directly from a Red Hat registry
that is outside OpenShift environment. This custom S2I image was not in
openshift catalog. In this lab, we will learn how to add the Spring Boot image
to the project catalog so that you can deploy the application directly
from your screen.

*Step 1:* Clean up the project that you created in the last lab.

Ensure you are in the right project by running `oc project` command. If
not, change your project by running `oc project spring-UserName`,
*replacing* the UserName with your own userid.

Clean up the contents of this project:

....
oc delete all --all
....

Verify that all the contents are gone by running `oc get all`

*Step 2:* Add the Spring Boot image stream.

We will use the image stream from the file
link:[https://raw.githubusercontent.com/hcs-company/openshift-springboot/master/springboot-imagestream.json].
Please go through the contents of this file.

....
{
    "kind": "ImageStream",
    "apiVersion": "v1",
    "metadata": {
        "name": "springboot"
    },
    "spec": {
        "tags": [
            {
                "name": "latest",
                "annotations": {
                    "description": "Spring Boot S2I Image CentOS based",
                    "iconClass": "icon-jboss",
                    "tags": "builder,springboot,java,maven",
                    "supports": "springboot,java:8,maven",
                    "version": "1.0"
                },
            "from": {
              "kind": "DockerImage",
              "name": "docker.io/veermuchandi/spring-mvn-base:latest"
            }
            }
        ]
    }
}
....

Notice, that this json points to the Spring Boot S2I builder Image on
docker hub. Also note the tags used in this imagestream. The tag
`builder` will display this in the catalog.

You have two ways to add this to the catalog. 1. Add from command line
2. Add using the web console

'''''

To add using CLI run the `oc create` command as under -

....
$ oc create -f https://raw.githubusercontent.com/hcs-company/openshift-springboot/master/springboot-imagestream.json

imagestream.image.openshift.io/springboot created
....

Check by running `oc get is`

You can also search your spring boot image by running the following
command

....
$ oc new-app --search springboot

Image streams (oc new-app --image-stream=<image-stream> [--code=<source>])
-----
springboot
  Project: hco-UserName
  Tags:    latest
....

'''''

To add using the web console, select `Add to Project`, and then
`Import YAML/JSON` tab on the top. Then you can copy paste the above
imagestream contents into the text box and press `Create` button.

*Step 3*

Now use that S2I image to deploy your sample spring boot application
link:[https://github.com/RedHatWorkshops/spring-sample-app] on OpenShift
using your experience from the previous labs.

....
$ oc new-app springboot~https://github.com/hcs-company/spring-sample-ap --name springboot

--> Found image c3ddd9e (2 years old) in image stream "hco-mkerker/springboot" under tag "latest" for "springboot"

    Spring Boot Maven 3
    -------------------
    Platform for building and running Spring Boot applications

    Tags: builder, java, java8, maven, maven3, springboot

    * A source build using source code from https://github.com/hcs-company/spring-sample-app will be created
      * The resulting image will be pushed to image stream tag "springboot:latest"
      * Use 'start-build' to trigger a new build
    * This image will be deployed in deployment config "springboot"
    * Port 8080/tcp will be load balanced by service "springboot"
      * Other containers can access this service through the hostname "springboot"

--> Creating resources ...
    imagestream.image.openshift.io "springboot" created
    buildconfig.build.openshift.io "springboot" created
    deploymentconfig.apps.openshift.io "springboot" created
    service "springboot2" created
--> Success
    Build scheduled, use 'oc logs -f bc/springboot' to track its progress.
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/springboot'
    Run 'oc status' to view your app.

....

Congratulations!! you have learnt to make an image stream available in
your project.

*If you got a question in mind* - _Well how can I make this image
available for everyone?_ Pat yourself on your back.. or ask your
colleague to do it ;). You are thinking right. All you need to do is
tell your openshift cluster administrator. +
*Answer* The cluster administrator will add the image to the `openshift`
project and everyone will start seeing it.
